language: python

jobs:
    include:
        - name: "Unit tests"
          stage: test
          python: "3.7"
          script: coverage run --source='.' manage.py test

        - name: "Lint"
          stage: test
          python: "3.7"
          script: black . --check
