language: python

jobs:
    include:
        - name: Unit tests
          stage: test
          python: "3.7"
          env:
              - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
          services:
              - postgresql
          before_script:
              - psql -c 'create database travis_ci_test;' -U postgres
          script: coverage run --source='.' manage.py test
          after_script: coverage report

        - name: Lint
          stage: test
          python: "3.7"
          script: black . --check

        - name: Deployment checklist
          stage: test
          python: "3.7"
          script: python manage.py check --deploy

env:
    global:
        - SECRET_KEY=565c9d74-6a8d-42fd-8f69-3c6f9f23c62d
