language: python

jobs:
    include:
        - name: "Unit tests"
          stage: test
          python: "3.7"
          env:
              - DATABASE_URL=postgres://postgres@localhost/postgres
          services:
              - postgresql
          before_script:
              - psql -c 'create database travis_ci_test;' -U postgres
          script: coverage run --source='.' manage.py test

        - name: "Lint"
          stage: test
          python: "3.7"
          script: black . --check
