language: python

jobs:
    include:
        - name: "Unit test"
          stage: test
          script: coverage run --source='.' manage.py test

        - name: "Lint"
          stage: test
          script: black . --check
