language: python
jobs:
    include:
        - name: Unit tests
          stage: test
          python: "3.7"
          env:
              - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
          services:
              - postgresql
          before_script:
              # add a postgres database
              - psql -c 'create database travis_ci_test;' -U postgres
              # enable Code Climate coverage
              # https://docs.codeclimate.com/docs/travis-ci-test-coverage
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build
          script: coverage run --source='.' manage.py test
          after_script:
              - coverage report
              - coverage xml
              - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

        - name: Lint
          stage: test
          python: "3.7"
          script: black . --check

        - name: Safety check
          stage: test
          script: safety check

        - name: Deployment checklist
          stage: test
          python: "3.7"
          script: python manage.py check --deploy

env:
    global:
        - SECRET_KEY=*&_vta+lomg9)329cbtosyv0u-+%xj&cr40$u70rqsjx5=hz5-
        # Test Reporter ID for CodeClimate
        - secure: rRJ/jaogzjU2kgzuq6Pov3KCWm/cDzKL2WDo6soLD7GivZUoKds3mYst15/TgidSL24DWmSD6AdM6Z45kanAzytKgzzLn4PuhU/aXUdue9CeR/08aAZNzZSN+oa5Y+9WuSQJl4aCF4/OxzrWVL7eyoWFxZYiy0Cy1jpEMKJViTXa7ZkPpHDIC9AP30i6YJDoVrVP0YUZWDUZWSXiuEwyq2FP4wfWfdn1vDa6ZeZpv+w6SbTaISk6BhOECiLI7h9hl3G3Ff7Znc6tp9YoARJ/lyOSsJ5cp+9tBsrlDnDjcidoOX7w96R1DQtFzYXtXLNbZFqwkdYYDOgk0RL96e03jdG20TWLyRwUDtPaZa1AdRWD3Y8TM5thrSHJyyXGxRhGft0/GsRdB3L0MWaAaYbfAv6vph/lKPgfFfNM1vm9+fRLe5UsLdufJukBZDAmUwipgM44YAhMDDcVAdmCKpEfXveTruFpCF0FkaXDIhKpFcrRGMDKJNr3EXien26y1ny4ekg8diwRWReQqeQ4RCwmNWe1Tv9haDql9DEVZUfY2OHIoAbWbHU5wBO6yWG/ciuv+i1Ou2jRD4jFhrWQuGh+tHHNfu7DymTrRA2O0W2DoM67fKyFT0bwgdjJB6xG4RCB6fUCKoXtQbYJleFczINO/iZacoRM3pa0OHu7rOoMUUI=
