language: python
jobs:
    include:
        - name: Unit tests
          stage: test
          python: "3.7"
          env:
              - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
          services:
              - postgresql
          before_script:
              # add a postgres database
              - psql -c 'create database travis_ci_test;' -U postgres
          script: coverage run --source='.' manage.py test
          after_script:
              - coverage report

        - name: Lint
          stage: test
          python: "3.7"
          script: black . --check

        - name: Deployment checklist
          stage: test
          python: "3.7"
          script: python manage.py check --deploy

        - name: Safety check
          stage: test
          script: safety check

        - name: Radon checks
          stage: test
          script: >-
              radon cc .
              && radon mi .

env:
    global:
        - SECRET_KEY="*&_vta+lomg9)329cbtosyv0u-+%xj&cr40$u70rqsjx5=hz5-"
