version: "3"

services:
    app:
        image: python:3
        ports:
            - 8000:8000
        command: >-
            bash -c "
            pip install --no-cache-dir -r requirements.txt
            && python manage.py collectstatic --noinput
            && python manage.py migrate
            && python manage.py runserver_plus 0.0.0.0:8000
            "
        stdin_open: true
        tty: true
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        links:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres@postgres/postgres

    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
